import type { POProfile, BankUtilization, RiverStation, Project } from "./types";

// Static session list removed — sessions are now loaded from Supabase via /api/sessions

export const KPI_DATA = {
  disbursement: {
    value: "BDT 93.58B",
    label: "Total Disbursement FY2024-25",
    change: "+23.89% YoY",
    trend: "up" as const,
  },
  recovery: {
    value: "99.21%",
    label: "Recovery Rate",
    change: "Excellent",
    trend: "stable" as const,
  },
  pos: {
    value: "278",
    label: "Partner Organizations",
    change: "Active",
    trend: "stable" as const,
  },
  members: {
    value: "20.7M",
    label: "Total Members",
    change: "93.67% Women",
    trend: "up" as const,
  },
};

export const PROGRAM_DATA = [
  { name: "Agrosor", value: 48.49, color: "#7c3aed" },
  { name: "Jagoron", value: 32.14, color: "#06b6d4" },
  { name: "Sufolon", value: 6.09, color: "#10b981" },
  { name: "Buniad", value: 0.99, color: "#f59e0b" },
  { name: "Others", value: 12.29, color: "#4a4a68" },
];

export const PO_PROFILES: POProfile[] = [
  {
    id: "jcf",
    name: "Jagorani Chakra Foundation (JCF)",
    tier: "C",
    recoveryRate: 96.8,
    par30: 4.2,
    compliance: 58,
    members: 420000,
    outstanding: 8.4,
    trend: "down",
    alert: "CRITICAL: Recovery dropping. 4 audit findings (2 CRITICAL). Grade D compliance.",
  },
  {
    id: "brac",
    name: "BRAC",
    tier: "A",
    recoveryRate: 99.8,
    par30: 0.2,
    compliance: 95,
    members: 3200000,
    outstanding: 48.2,
    trend: "stable",
  },
  {
    id: "asa",
    name: "ASA",
    tier: "A",
    recoveryRate: 99.7,
    par30: 0.3,
    compliance: 93,
    members: 2800000,
    outstanding: 42.1,
    trend: "stable",
  },
  {
    id: "tmss",
    name: "TMSS",
    tier: "A",
    recoveryRate: 99.5,
    par30: 0.5,
    compliance: 91,
    members: 890000,
    outstanding: 15.6,
    trend: "up",
  },
  {
    id: "esdo",
    name: "ESDO",
    tier: "B",
    recoveryRate: 98.9,
    par30: 1.1,
    compliance: 78,
    members: 560000,
    outstanding: 9.8,
    trend: "down",
    alert: "Recovery rate declining trend detected.",
  },
  {
    id: "padakhep",
    name: "Padakhep Manabik Unnayan Kendra",
    tier: "B",
    recoveryRate: 98.2,
    par30: 1.8,
    compliance: 72,
    members: 320000,
    outstanding: 5.4,
    trend: "down",
    alert: "Elevated staff turnover rate impacting operations.",
  },
  {
    id: "shakti",
    name: "Shakti Foundation",
    tier: "A",
    recoveryRate: 99.3,
    par30: 0.7,
    compliance: 88,
    members: 680000,
    outstanding: 11.2,
    trend: "stable",
  },
  {
    id: "buro",
    name: "BURO Bangladesh",
    tier: "B",
    recoveryRate: 98.7,
    par30: 1.3,
    compliance: 80,
    members: 445000,
    outstanding: 7.9,
    trend: "stable",
  },
];

export const BANK_UTILIZATION: BankUtilization[] = [
  { name: "NCC Bank", allocated: 200, utilized: 160, percentage: 80 },
  { name: "Sonali Bank", allocated: 250, utilized: 175, percentage: 70 },
  { name: "Agrani Bank", allocated: 200, utilized: 130, percentage: 65 },
  { name: "Janata Bank", allocated: 200, utilized: 110, percentage: 55 },
  { name: "BASIC Bank", allocated: 150, utilized: 72, percentage: 48 },
];

export const RIVER_STATIONS: RiverStation[] = [
  {
    name: "Surma",
    location: "Sylhet Sadar",
    currentLevel: 10.82,
    dangerLevel: 10.5,
    warningLevel: 9.5,
    status: "danger",
  },
  {
    name: "Kushiyara",
    location: "Sherpur, Moulvibazar",
    currentLevel: 9.14,
    dangerLevel: 9.0,
    warningLevel: 8.2,
    status: "danger",
  },
  {
    name: "Old Surma",
    location: "Sunamganj",
    currentLevel: 7.8,
    dangerLevel: 8.1,
    warningLevel: 7.2,
    status: "warning",
  },
  {
    name: "Padma",
    location: "Rajshahi",
    currentLevel: 14.2,
    dangerLevel: 16.5,
    warningLevel: 15.0,
    status: "normal",
  },
];

export const PROJECTS: Project[] = [
  {
    id: "raise",
    name: "RAISE",
    funder: "World Bank",
    amount: "$530M",
    burnRate: 82,
    status: "on-track",
    dueIn: "IFR due 18d",
  },
  {
    id: "smart",
    name: "SMART",
    funder: "ADB",
    amount: "$100M",
    burnRate: 41,
    status: "at-risk",
    dueIn: "Q3 review",
  },
  {
    id: "rmtp",
    name: "RMTP",
    funder: "IFAD",
    amount: "$80M",
    burnRate: 94,
    status: "closing",
    dueIn: "Closing phase",
  },
  {
    id: "reopa",
    name: "REOPA",
    funder: "EU / DFID",
    amount: "$45M",
    burnRate: 67,
    status: "on-track",
  },
  {
    id: "prosper",
    name: "PROSPER",
    funder: "USAID",
    amount: "$35M",
    burnRate: 55,
    status: "on-track",
  },
  {
    id: "swisscontact",
    name: "PACE-B",
    funder: "SwissContact",
    amount: "$22M",
    burnRate: 78,
    status: "on-track",
  },
  {
    id: "katalyst",
    name: "KATALYST III",
    funder: "SDC",
    amount: "$18M",
    burnRate: 89,
    status: "at-risk",
    dueIn: "Low disbursement",
  },
  {
    id: "jeeon",
    name: "JEEON",
    funder: "FCDO",
    amount: "$15M",
    burnRate: 45,
    status: "on-track",
  },
];

export const FUND_SOURCES = [
  { name: "GoB Revenue Budget", amount: 2840, utilized: 2250, currency: "Cr BDT" },
  { name: "World Bank (IDA)", amount: 1840, utilized: 1510, currency: "Cr BDT" },
  { name: "ADB Loan", amount: 680, utilized: 280, currency: "Cr BDT" },
  { name: "IFAD Credit", amount: 520, utilized: 490, currency: "Cr BDT" },
  { name: "CES (Commercial)", amount: 1000, utilized: 780, currency: "Cr BDT" },
  { name: "PKSF Own Fund", amount: 3200, utilized: 3200, currency: "Cr BDT" },
  { name: "EU Grant", amount: 180, utilized: 121, currency: "Cr BDT" },
  { name: "USAID Grant", amount: 140, utilized: 77, currency: "Cr BDT" },
];

export const ACTIVE_ALERTS = [
  {
    id: "1",
    severity: "critical" as const,
    title: "JCF Recovery Rate Critical Drop",
    detail: "96.8% — below threshold. 2 critical audit findings unresolved.",
    time: "15m ago",
  },
  {
    id: "2",
    severity: "warning" as const,
    title: "RAISE IFR Submission Due",
    detail: "World Bank Interim Financial Report due in 18 days.",
    time: "1h ago",
  },
  {
    id: "3",
    severity: "warning" as const,
    title: "Sylhet Flood — Surma at Danger Level",
    detail: "10.82m vs 10.50m danger mark. 340 borrowers in affected zones.",
    time: "2h ago",
  },
  {
    id: "4",
    severity: "info" as const,
    title: "SMART Project ADB Review",
    detail: "41% disbursement flagged. Review scheduled Q3.",
    time: "4h ago",
  },
  {
    id: "5",
    severity: "info" as const,
    title: "NCC Bank CES at 80% Utilization",
    detail: "BDT 160 Cr of 200 Cr utilized. Approaching ceiling.",
    time: "6h ago",
  },
];

export const PSYCHOMETRIC_PROFILES = [
  {
    id: "jcf",
    name: "JCF",
    fullName: "Jagorani Chakra Foundation",
    tier: "C",
    overallScore: 52,
    dimensions: [
      { name: "Financial Health", score: 42, max: 100 },
      { name: "Governance Quality", score: 48, max: 100 },
      { name: "Operational Resilience", score: 55, max: 100 },
      { name: "Social Impact", score: 72, max: 100 },
      { name: "Adaptive Capacity", score: 44, max: 100 },
    ],
    riskFlag: "HIGH RISK",
    recommendation: "Immediate intervention required. Probationary review.",
  },
  {
    id: "brac",
    name: "BRAC",
    fullName: "BRAC Bangladesh",
    tier: "A",
    overallScore: 96,
    dimensions: [
      { name: "Financial Health", score: 98, max: 100 },
      { name: "Governance Quality", score: 95, max: 100 },
      { name: "Operational Resilience", score: 97, max: 100 },
      { name: "Social Impact", score: 99, max: 100 },
      { name: "Adaptive Capacity", score: 91, max: 100 },
    ],
    riskFlag: "STABLE",
    recommendation: "Continue strategic partnership. Expand collaboration.",
  },
  {
    id: "esdo",
    name: "ESDO",
    fullName: "Eco-Social Development Organization",
    tier: "B",
    overallScore: 74,
    dimensions: [
      { name: "Financial Health", score: 71, max: 100 },
      { name: "Governance Quality", score: 76, max: 100 },
      { name: "Operational Resilience", score: 73, max: 100 },
      { name: "Social Impact", score: 82, max: 100 },
      { name: "Adaptive Capacity", score: 68, max: 100 },
    ],
    riskFlag: "WATCH",
    recommendation: "Monitor recovery rate decline. Capacity building recommended.",
  },
  {
    id: "tmss",
    name: "TMSS",
    fullName: "Thengamara Mohila Sabuj Sangha",
    tier: "A",
    overallScore: 89,
    dimensions: [
      { name: "Financial Health", score: 92, max: 100 },
      { name: "Governance Quality", score: 88, max: 100 },
      { name: "Operational Resilience", score: 87, max: 100 },
      { name: "Social Impact", score: 94, max: 100 },
      { name: "Adaptive Capacity", score: 84, max: 100 },
    ],
    riskFlag: "STABLE",
    recommendation: "Strong performance. Consider for pilot programs.",
  },
];
