"use client";

import { useState } from "react";
import { Download, Maximize2, X } from "lucide-react";
import type { OutputPanel } from "@/lib/types";

interface OutputCardProps {
  item: OutputPanel;
  iconColor: string;
  iconBg: string;
  tabIcon: React.ElementType;
}

function ExpandModal({
  item,
  iconColor,
  tabIcon: Icon,
  onClose,
}: {
  item: OutputPanel;
  iconColor: string;
  tabIcon: React.ElementType;
  onClose: () => void;
}) {
  return (
    <div
      onClick={onClose}
      style={{
        position: "fixed", inset: 0, zIndex: 900,
        background: "rgba(0,0,0,0.65)", backdropFilter: "blur(6px)",
        display: "flex", alignItems: "center", justifyContent: "center",
        padding: "24px",
      }}
    >
      <div
        onClick={(e) => e.stopPropagation()}
        style={{
          background: "var(--bg-1)",
          border: "1px solid var(--glass-border)",
          borderRadius: "14px",
          width: "100%",
          maxWidth: "860px",
          maxHeight: "85vh",
          display: "flex",
          flexDirection: "column",
          overflow: "hidden",
          boxShadow: "0 24px 60px rgba(0,0,0,0.4)",
        }}
      >
        {/* Modal header */}
        <div
          style={{
            display: "flex", alignItems: "center", gap: "10px",
            padding: "14px 16px", borderBottom: "1px solid var(--glass-border)",
            flexShrink: 0,
          }}
        >
          <div
            style={{
              width: "30px", height: "30px", borderRadius: "8px",
              background: `${iconColor}18`,
              display: "flex", alignItems: "center", justifyContent: "center",
            }}
          >
            <Icon size={15} color={iconColor} strokeWidth={2} />
          </div>
          <div style={{ flex: 1, minWidth: 0 }}>
            <p style={{ color: "var(--text-primary)", fontSize: "13px", fontWeight: 700, margin: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
              {item.title}
            </p>
            <p style={{ color: "var(--text-dim)", fontSize: "9px", fontFamily: "var(--font-jetbrains-mono), monospace", margin: "2px 0 0" }}>
              {item.timestamp?.toLocaleString([], { dateStyle: "medium", timeStyle: "short" }) ?? ""}
            </p>
          </div>
          <button
            onClick={onClose}
            style={{ background: "rgba(255,255,255,0.06)", border: "1px solid var(--glass-border)", borderRadius: "7px", padding: "6px", cursor: "pointer", color: "var(--text-muted)", display: "flex" }}
          >
            <X size={14} />
          </button>
        </div>
        {/* Modal body */}
        <div
          className="output-content"
          style={{ flex: 1, overflowY: "auto", overflowX: "hidden", padding: "20px 24px" }}
          dangerouslySetInnerHTML={{ __html: item.html }}
        />
      </div>
    </div>
  );
}

export default function OutputCard({ item, iconColor, iconBg, tabIcon: Icon }: OutputCardProps) {
  const [expanded, setExpanded] = useState(false);

  const handleExport = () => {
    const blob = new Blob(
      [
        `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${item.title}</title>` +
        `<style>body{font-family:'Segoe UI',sans-serif;background:#0a0a20;color:#a0a0c0;padding:32px;max-width:900px;margin:auto;}</style>` +
        `</head><body><h1 style="color:#a78bfa;font-size:18px;margin-bottom:4px;">${item.title}</h1>` +
        `<p style="color:#6a6a90;font-size:11px;margin-bottom:24px;">Generated by Freya AI · PKSF Intelligence · ${item.timestamp?.toLocaleString() ?? new Date().toLocaleString()}</p>` +
        item.html +
        `</body></html>`,
      ],
      { type: "text/html" }
    );
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    const safeName = item.title.replace(/[^a-z0-9]/gi, "_").toLowerCase().replace(/^_+|_+$/g, "") || "freya_output";
    a.download = `${safeName}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <>
      {expanded && (
        <ExpandModal
          item={item}
          iconColor={iconColor}
          tabIcon={Icon}
          onClose={() => setExpanded(false)}
        />
      )}

      <div
        style={{
          background: "var(--glass-bg)",
          border: "1px solid var(--glass-border)",
          borderRadius: "12px",
          overflow: "hidden",
          display: "flex",
          flexDirection: "column",
          flex: 1,
          minHeight: 0,
        }}
      >
        {/* Card header */}
        <div
          style={{
            display: "flex", alignItems: "center", gap: "10px",
            padding: "10px 12px",
            borderBottom: "1px solid var(--glass-border)",
            background: "rgba(255,255,255,0.01)",
          }}
        >
          <div
            style={{
              width: "28px", height: "28px", borderRadius: "8px",
              background: iconBg,
              display: "flex", alignItems: "center", justifyContent: "center",
              flexShrink: 0,
            }}
          >
            <Icon size={14} color={iconColor} strokeWidth={2} />
          </div>
          <div style={{ flex: 1, minWidth: 0 }}>
            <div
              style={{
                color: "var(--text-primary)", fontSize: "12px", fontWeight: 600,
                overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap",
              }}
            >
              {item.title}
            </div>
            <div
              suppressHydrationWarning
              style={{ color: "var(--text-dim)", fontSize: "9px", fontFamily: "var(--font-jetbrains-mono), monospace", marginTop: "1px" }}
            >
              {item.timestamp?.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) ?? ""}
            </div>
          </div>
          {/* Quick expand */}
          <button
            onClick={() => setExpanded(true)}
            title="Expand"
            style={{
              background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.06)",
              borderRadius: "6px", padding: "4px 6px", cursor: "pointer",
              color: "var(--text-dim)", display: "flex",
            }}
          >
            <Maximize2 size={11} />
          </button>
        </div>

        {/* Card body — fills remaining height, scrolls if content overflows */}
        <div
          className="output-content"
          style={{ flex: 1, padding: "12px 14px", overflowY: "auto", overflowX: "hidden", minHeight: 0 }}
          dangerouslySetInnerHTML={{ __html: item.html }}
        />

        {/* Card footer */}
        <div
          style={{
            display: "flex", gap: "6px", padding: "8px 12px",
            borderTop: "1px solid var(--glass-border)",
            background: "rgba(255,255,255,0.01)",
          }}
        >
          <button
            onClick={handleExport}
            style={{
              display: "flex", alignItems: "center", gap: "5px",
              padding: "5px 10px", borderRadius: "6px",
              background: `${iconColor}12`,
              border: `1px solid ${iconColor}25`,
              color: iconColor,
              fontSize: "10px", fontWeight: 600, cursor: "pointer",
              fontFamily: "var(--font-jetbrains-mono), monospace",
              transition: "all 0.15s",
            }}
          >
            <Download size={11} strokeWidth={2} />
            Export HTML
          </button>
          <button
            onClick={() => setExpanded(true)}
            style={{
              display: "flex", alignItems: "center", gap: "5px",
              padding: "5px 10px", borderRadius: "6px",
              background: "rgba(255,255,255,0.04)",
              border: "1px solid rgba(255,255,255,0.07)",
              color: "#6a6a90",
              fontSize: "10px", fontWeight: 600, cursor: "pointer",
              fontFamily: "var(--font-jetbrains-mono), monospace",
            }}
          >
            <Maximize2 size={11} strokeWidth={2} />
            Full View
          </button>
        </div>
      </div>
    </>
  );
}
